"""Sentetik olcum seti -- soru_uret.py tarafindan uretildi.

Her soru, karsisindaki maddeden uretildi; dogru cevap o maddedir.
Sentetik oldugu icin gercek kullanici sorularindan daha iyimser sonuc
verir; mutlak dogruluk olcusu degil, degisiklikleri karsilastirma
olcegidir.
"""

SORULAR: list[tuple[str, str, str | None]] = [
    ('İfayete katılmak için ne gerekiyor?', '10713', '45'),
    ('Öğrenci, hangi semineri en geç dördüncü yarıyılın başında almak zorundadır?', '45096', '24'),
    ('Üyeleri iki yıldır olan yönetim kurulu üyelerinin görev süresi ne zaman sona erer?', '33927', '10'),
    ('Bir dersin bir yarıyılda açık kalması için ne şartlar gereklidir?', '34876', '13'),
    ('Türkiye Eğitim Bakanlığı’nın Yönetim Kurulu, hangi faaliyetleri yapmamalıdır?', '41256', '11'),
    ('Belge tarihi hangi alanda bulunur?', '2646', '12'),
    ('Müşterim, sigorta şirketlerinin malî tablolarını hangi kuruluşlar tarafından denetlenir?', '5684', '18'),
    ("Türkiye Cumhuriyeti Anayasası'na ve ÖSYM mevzuatına sadakatle bağlı kalmak zorundalar mı?", '15518', '14'),
    ('İhracatçı, C şekerini yurtiçinde satmaya devam ederken ihraç ön izni belgesi ne zaman düzenlenir?', '18913', '11'),
    ('İhalede geçici teminat nedir?', '13043', '30'),
    ('İlana çıkışı olmasa da ihalelere ne yapar?', '24571', 'Geçi̇ci̇ 1'),
    ('Sertifikanın iptalini gerektiren hallerden birisine yönelik ihbar ve şikâyeti ne şekilde değerlendirilir?', '18302', '21'),
    ('Üniversite, hangi işlemleri gerçekleştirmeli?', '36050', '4'),
    ('İhalede geçici teminat miktarını ne belirler?', '34547', '9'),
    ('Uzmanlık tezi kabul edilmezse ne olur?', '17236', '25'),
    ('Öğrenci, dönem projesi başarısız olarak değerlendirildiğini nasıl belirtir?', '38826', '38'),
    ('İşçi sendikası yetkisi düşer mi? Arabuluculuk var mı?', '6356', '49'),
    ('Bakanlara tahsis edilen özel konutlarda 1984 bulunan demirbaş eşyası neresinden gelir?', '848345', 'Geçici 7'),
    ('Kesimhane yetkililerinin ne yapmaları gerekiyor?', '15535', '10'),
    ('Kişiniz, ibra edilmeyen yönetim kurulu üyelerinin aleyhinde hukuki davalar açılabilmesi için ne gerekiyor?', '31245', '91'),
    ('Sınıfımıza sınav sonuçlarını ne zaman gönderebiliriz?', '36033', '36'),
    ('Türkiye Mühendis ve Mimari Odaları Birliği Meslek İçi Yönetmeliklerinde ne uygulanır?', '20515', '22'),
    ('Türkiye Boğazlarında Transit Nitelik Devam Ediyor Mu?', '13104', '34'),
    ('Nisan ayında hazırlık eğitiminde derslere ne oranında devam etmek zorunludur?', '22766', '11'),
    ("Atatürk Orman Çiftliği'ne mukarrer yeni toptancı hali için arazi, Belediyece kullanımdan çıkarmak için ne yapmalıdır?", '2015', '1'),
    ('Biraların ne gibi özellikler olmalı?', '315481', '520'),
    ('Öğretim elemanı, dönem başlamasından önce nasıl görevlendirilir?', '40366', '46'),
    ('İşyeri sahibi kapatma kararı ne zaman alınır?', '20059207', '40'),
    ("Sonuç raporu ne zaman TÜSEB'e iletilir?", '24458', '10'),
    ('Hangi amirin emri yerine getirilmez?', '40130', '22'),
    ('Öğrenci, nasıl intibakı yapılır?', '22828', '18'),
    ('Kütahya Sağlık Bilimleri Üniversitesi Teknoloji Transfer Ofisi, hangi usul ve esasları düzenler?', '40645', '1'),
    ("Danışma Kurulu'nun hangisi?", '36241', '4'),
    ('Akrilonitril ihlaliyle ilgili ne bilmek istersin?', '16068', '2'),
    ('Karar nisabı hangi ajans tarafından alınır?', '38502', '12'),
    ('Ön inceleme ne zaman yapılmış?', '17007', '1'),
    ('Ölüme mahkum edilen, düşman karşısında kaçan mıydı?', '1632', '69'),
    ('Kamu İktisadi Teşebbüsleri Sicilini ne zaman ve ne şekilde hazırlamalıyım?', '39880', '3'),
    ("Türkiye'deki eğitim kurumları için sınav hizmetleri sunmakta mı?", '31207', '6'),
    ('Nasıl bilgisayarların çevreye duyarlı tasarım gerekliliklerine uygunluğu ölçülüyor?', '38452', '6'),
    ('Türkiye Taşkömürü Kurumu Genel Müdürünün hangi görevi olduğu?', '20078', '4'),
    ('Eskişehir Teknik Üniversitesi Havacılık ve Uzay Bilimleri Fakültesi Dekanını kimdir?', '42632', '4'),
    ('Seçim müdürlüklerinin adalet müfettişleri tarafından denetlenmesi ne anlama geliyor?', '38532', '1'),
    ('Türkiye’de 2009-2011 yılları arasında ithalatın hacmi ne kadar önemli ölçüde artmış?', '19557', '23'),
    ('Devlet Su İşleri, kuyuları nasıl açar?', '167', '7'),
    ('El yazısı ve imzalamış olmayan başvurular kabul edilmez mi?', '11269', '30'),
    ('Kanalizasyonu ne zaman yapmalıyım?', '11783', '1'),
    ('İlk yardım ve ambulans servisinin ne yapmaları gerekiyor?', '631500', '23'),
    ('Solunum fonksiyon testlerini kim yapar?', '39291', '11'),
    ('Hangi ihalede isteklilerin teklifleri, politika hedeflerine etkisi ölçütsel olarak değerlendirilir?', '13717', '24'),
    ('Üniversitede iki müdür yardımcısı görevindeyim. Müdürün görevi sona erince de görevim sona erer mi?', '38950', '10'),
    ('Danıştayda ilk derecede dava için ne kadar ücret ödenir?', '36009', '15'),
    ("Türkiye Cumhuriyet Merkez Bankası'nın döviz alış kuru ne zaman alınır?", '4721', '851'),
    ('Bitki ürünleri bayi ve toptancı ne zaman satış yerlerini açabilir?', '43926', '32'),
    ('Ticaret unvanı ve işletme adına ilişkin diğer hususlarda ne yaparız?', '19399', '6'),
    ('Teftiş sonucunda müfettişin hangi kararı alır?', '8812580', '40'),
    ('Hangi mallarda pazarlık usulü ile ihale yapılabilir?', '34547', '30'),
    ('Ülkemde gıda maddelerinin muamelesi ne tür şartlara sahip olmalıdır?', '315481', '5'),
    ('İhracata yönelik devlet yardımını ne tarihde ve ne numara bir kararla yürürlüğe koyulmuştur?', '16275', '3'),
    ('Kasa hesabına ne ekleyebilirim? Kanun ne belirtiyor?', '20357', '11'),
    ('Yevmiyeyi ne kadar artar?', '6245', '35'),
    ("Türkiye Büyük Millet Meclisi'nden müfettişliğe yeniden atanmış bir kişinin kıdem sırası hangi müfettişlerden önceki?", '39097', '44'),
    ('Necmettin Erbakan Üniversitesi Diş Hekimliği Fakültesi Dekanının ne görevi olduğunu ne anlama gelirsin?', '40312', '4'),
    ('Bu maddenin ne kapsadığını bilmeyen kişi: "Temin faaliyetlerinde görev alacak bireyleri neye aittir?', '38966', '2'),
    ('Sözleşme tarihinden üç yıl sonra ve sözleşmenin bitiminden bir yıl önce, çadır alanlarının düzenlemesi mümkün mü?', '39544', '14'),
    ('Üniversite yönetim kurulunu ne demek?', '38473', '4'),
    ('Türkiye Büyük Millet Meclisi Kanunu 480/1 maddesi uyarınca, yüklenicinin ölümü sözleşmenin devamına neden olur mu?', '5738', '36'),
    ('Ne zaman Lisansüstü Eğitim ve Öğretim Yönetmeliğinin uygulanması başlamış?', '24561', 'Geçi̇ci̇ 1'),
    ('Bu bölgelerde kara yollarının güvenliğinin nasıl sağlanması gerektiği hangi yetkili komutanlığa aittir?', '835949', '7'),
    ("Yönlendirme Kurulu'nun projeleri hangi yıla ait olacak?", '155', '6'),
    ('Nasıl istatistik verilerinin gizliliğini sağlamak gerekiyor?', '10429', '12'),
    ('Hangi eşyalar dampinge karşı önlemler yürürlüğe konmuştur?', '20295', '1'),
    ('Müfettişlerin yurtdışına gönderilebilir mi?', '12366', '58'),
    ('Enstitünün faaliyet alanları nedir?', '39843', '5'),
    ('Soruyu Sırbistan Hukukunda nasıl yapılır?', '15735', '5'),
    ('Mevcut müdahalede, davayı kim takip edebilir?', '6100', '68'),
    ('Danışma Kurulunun uzun vadeli plan değerlendirmeleri konusunda ne bildiğini sormuş musun?', '33945', '13'),
    ('Öğrenci ders muafiyet talebinde bulunurken, hangi derslerin muaf edileceği belirtilerine göre karar verilir?', '40291', '33'),
    ('Üyeliği iptal edilmiş ihraççı üyeler hakkında hangi maddenin hükmü uygulanır?', '19951', 'Geçi̇ci̇ 2'),
    ('Vergi Müfettişleri mi bildirimlerini yazılı olarak mı yapar?', '38504', '38'),
    ('SJMMHK tescil belgesi almak için hangi belgeler gereklidir?', '10703', '10'),
    ('Kanunun ne amacı?', '20168520', '1'),
    ('Sınırlı kaptan olmak için hangi yeterliklerden birini yerine getirilmesi gerekir?', '40941', '8'),
    ('Müdürün görevleri ne zaman sona erer?', '34776', '8'),
    ('Dava dairesi başkanı, davaya bakmakta çekinme halinde olursa, hangi kurul tarafından karar verilir?', '2577', '56'),
    ('Ödül ve sponsorluk işlemlerinin hangi tarihteki kanun ve kararı tarafından yürürlüğe koyulmuştur?', '42340', '43'),
    ('Öğrenci, vefat eden ailesiyle ilgili 7 günlük izin talebi için nasıl hareket eder?', '23978', '21'),
    ("Bayburt Üniversitesi Spor Eğitimi Uygulama ve Araştırma Merkezi'nin amacı nedir?", '38378', '1'),
    ('Atıksu hizmetlerinin ücretlendirme durumunu bilmiyor musun?', '14390', '17'),
    ('Kanun Hükmünde Kararnamenin düzenlemelerini ne zaman uygulanır?', '665', 'Geçi̇ci̇ 5'),
    ('Soruyu Sizce hangi derleme mükellefi bu maddenin cevabı olacaktır?', '6279', '10'),
    ('Spor Federasyonunun merkez teşkilatının hangi organlardan oluştuğunu belirten bir maddenir?', '42342', '5'),
    ('Üniversitenin alım tutanakları ne tür bir tutanaklar olur?', '38295', '27'),
    ("Şube Yönetim Kurulu'nun üyeleri kaçtır?", '9890', '61'),
    ('Türkiye Ceza Kanunu kapsamında suç teşkil eden fiil ve davranışlarda bulunanlar hakkında ne uygulanır?', '18407', '13'),
    ("Devlet Memurları Kanunu'nun 68. maddesinde belirtilen genel şartları nelerdir?", '34593', '7'),
    ('Ücretlerin uygulanış şekli ne? Kanun 1/8 maddesi ne belirtiyor?', '10648', '12'),
    ('Türkiye Okul Sporları Federasyonu Genel Müdürlüğünü kim oluşturur?', '20109', '4'),
    ('Öğrenci yabancı dil yeterlik sınavından düşük not aldığını düşünüyor. Nasıl kabul edilebilir?', '41060', '9'),
    ('Yardımcı Müdür görev süresi ne?', '31186', '10'),
    ('Bu ihalede ne usul kullanacağız?', '14732', '25'),
    ("Türkiye Büyük Millet Meclisi'nin ilamlarının tavzi ve düzeltilmesinde hangi durumlarla ilgili olur?", '15615', '17'),
    ("Nasılsın? Yükseköğretim Kanunu'nun 14. maddesine dayanan yönetmelikin ne hakkında bilmiyorsun?", '31287', '3'),
    ("Nasıl belgeleri belgelendirirken Merkezi Yönetim Harcama Belgeleri Yönetmeliği'ni kullanır?", '23215', '23'),
    ('Kanunun 146ncı maddesindeki süre, geçici ihraç eşyasının serbest bölgeye alınması halinde ne olur?', '13472', '413'),
    ('Sınavın konuları nedir?', '34314', '19'),
    ('Kanal mı uygun şekilde genel kurul toplantılarına bakacak bir yetkili olacak?', '39277', '1'),
    ('Öğrenci, doktora programının amacı nedir?', '36048', '35'),
    ('Yardımcı sorun, yönetim kurulunun amacı doğrultusunda faaliyetlerin nasıl yürütüleceği konusunda bana ne söyledi?', '41280', '11'),
    ('Eğitim kurumunun yer alacağı binada hangi yerler bulunamaz?', '16923', '15'),
    ('Hangi hava seyrüsefer hizmet sağlayıcı kuruluşu, en az beş yıllık iş planını oluşturmalıdır?', '18573', '15'),
    ('Ekonomi Bakanlığı, soruşturma sonuçlarını ne sayfada buldun?', '18545', '2'),
    ('Neden enerji etiketlemesi konusunda yeni bir tebliğ geldi?', '34838', '9'),
    ('Vasiyetnamenin açılmasından sonra hangileri tebliğ olunur?', '65100', '37'),
    ('Merkezin ne tür faaliyetlerde bulunması gerekiyor?', '45143', '6'),
    ("Erzurum Teknik Üniversitesi'nin teknoloji transferi uygulama merkezi hakkında ne biliyor musun?", '40736', '1'),
    ('Eğitim ücretiyle nasıl karar verilir?', '11332', '20'),
    ('Kuralların ne anlama geldiğini anlayamadım. Yurt içindeki cumhurbaşkanı için kira bedeli var mı?', '2946', '5'),
    ('Türk Silahlı Kuvvetleri için alım süreci ne yapar?', '1548', '30'),
    ('Bakanlıkta cihaz tedarik eden işletmeciler hakkında bilgi vermek zorunda mı?', '24569', '14'),
    ('İhale komisyonu iş deneyimini gösteren belgelere ilişkin incelemeyi yapmaya yetkilidir mi?', '12911', '50'),
    ('Türkiye Ticaret Kanunu’nda, hangi tarihden itibaren sanayicilerin tarife kontenjanından faydalanabilecekleri?', '21285', '3'),
    ('Meslek içi eğitim ne zaman uygulanabilir?', '38248', '12'),
    ('Ürünün ihracatından sonra düzenlenebilir mi?', '38420', '22'),
    ('KPSS puanı düşük olan adayların sıralamasında neye göre değerlendirilir?', '19720', '19'),
    ('Eğitim müdürlüklerine 2024-2025 eğitim yılı sonuna kadar onayı teslim etmek mi?', '15970', 'Geçi̇ci̇ 22'),
    ('Sicili tutan icra memuru, hangi tarihten itibaren kayıtların rehin alacaklılarına yenileme isteği süresi sona erer?', '65165', '15'),
    ('Acente sözleşmeme icazesi vermediği takdirde ne sorumlu olur?', '6102', '108'),
    ("Danışma Kurulu'nun üyeleri ne tür kişilerden oluşur?", '45012', '12'),
    ('Adlî sicil bilgilerini verebilecek merciler kimdir?', '5352', '7'),
    ('Öğrenci, tezini jürinin savunulabilir olduğuna ilişkin görüşü ile birlikte enstitüne teslim etmesi gereken neyi?', '24561', '24'),
    ('Federasyon şubelerinde ne bulunması zorunludur?', '4721', '95'),
    ('Denetimle ilgili yetkilerimi kim alıyor?', '10677', '31'),
    ('Çarşı ve mahalle bekçileri görev bölgelerini terk etmek zorundalar mı?', '40130', '7'),
    ('Öğrenci, hangi durumlarda kayıtları yenilememe hakkı yok?', '45095', '16'),
    ('Kabul edilemez başvuru ile hızlandırılmış değerlendirme kararlarına karşı ne zaman başvurulabilir?', '21460', '101'),
    ('Öğrenci sınıf geçme durumunu nasıl açıklıyor?', '40396', '17'),
    ('Sahibinin şirketin hâkim şirketle ilişkisini incelemek üzere özel denetçiyi atanması gerekebiliyor mu?', '6102', '406'),
    ('Kanunun ne zaman kaldırıldı ve ne zaman uygulanmaya devam etti?', '703', '47'),
    ('Türkiye Büyük Millet Meclisi, hangi gelirleri üst Kurulun gelirlerinden ayrılacak?', '6112', '41'),
    ('Yüzde ne yapacak, Yönetim Kurulu Merkezi?', '31265', '11'),
    ('5 yıl süreyle Gökçeada ve Bozcaada’daki işletmelerin ne şart altında yararlanabilir?', '5084', 'Geçici 2'),
    ('Üniversitenin mal ve hizmet satışları ihalelerinde hangi usul uygulanır?', '39580', '27'),
    ('Türk Silahı Kuvvetleri bünyesinde temel hava trafik kontrol eğitimi kimin yetkili?', '17077', '9'),
    ('5 Harçlar ve tarifeler maddesinde yazılı görev hangileri iki şahit önünde görecek?', '32412', '33'),
    ('Spor Federasyonu tarafından istenen belgelerin hangi maddenin belirtili?', '42561', '23'),
    ('Milli Müdafaa Mükellefiyetiyle ticari işlerin kesilmesi durumunda hangi tazminat verilir?', '3634', '61'),
    ('Uluslararası bilgilendirme sisteminin kapsamını ne anlama geliyor?', '10715', '44'),
    ('Sınavda en az ne not almak gerekir?', '12366', '30'),
    ('Öğrenci, yeterlik çalışmasının sonuçlanması için hangi süre içinde kredili dersleri tamamlamak zorunda?', '38826', '51'),
    ("Danışma Kurulu'nun üye sayısı ve toplama tarihleri hangi maddeye aittir?", '40738', '12'),
    ('Türkiye Ticaret Bakanlığına ne bildirir Bakanlık, C şeker pazarlamasında?', '38671', '17'),
    ('Türkiye Ticaret Ticaret Tescilleri Kanunu’nda, üçüncü kişiler ne tespit edildikten sonra nezdinde itirazda bulunabilir?', '5042', '45'),
    ('Öğrenci yurt dışında bir üniversiteden gelen derslerin notunu hangi kurul tarafından belirlenir?', '40329', '47'),
    ('Kamu iktisadi teşebbüslerinin denetimleri sonucu Yıllık Raporlar, hangi ayın sonuna kadar Başkanlığa sunulur?', '15612', '32'),
    ('İthalat vergileri tutarının ne tarihten ne tarihe uygulanacağı?', '4458', '141'),
    ('Spora dayalı bahis ve şans oyunları düzenlemesiyle ilgili ne yapmam gerekiyor?', '12665', '6'),
    ('Hangi ürün ithalatının yerli üretim dalının ekonomik göstergelerinde maddi zarara yol açtığı iddia edilmiştir?', '41134', '7'),
    ('Öğrenci, tezsiz yüksek lisans programının hangi özelliği olduğunu bilmiyor?', '45090', '14'),
    ('Sözlü sınavda başarılı sayılmak için ne şarttır?', '39184', '32'),
    ('Ekli (II) ve (III) sayılı Cetvellerde yer alan unvanlı kadrolara atananların mali hakları ne zaman ödenir?', '375', 'Geçici 12'),
    ('Öğrenci, bu maddenin ne olduğunu bilemez: "Ne cezalar oda üyelerine verilebilir?', '6964', '33'),
    ('Rektör, üniversitenin yatırım programını hangi kurulunun onayı gerekiyor?', '2547', '13'),
    ('Bakanlık tarafından Spor Federasyonuna yapılan yardımların ne yapılamayacağı?', '42416', '41'),
    ('Kanunun hangi maddesi, rektör tarafından görevlendirilen personeli kimin ihtiyaçlarına karşı kullanır?', '34415', '15'),
    ('Hangi mallarda pazarlık usulü ile ihale yapılabilir?', '34381', '30'),
    ('Sözleşmeli personelin haftalık çalışma süresi ne?', '399', '20'),
    ('Müzeye bağışladığım eser envanter defterine ne eklenir?', '14360', '8'),
    ('Ürünün soruşturma konusu ülkeden ithalatı ne zaman olmuştur?', '19028', '19'),
    ('Sınava başvurulacak belgelerin hangi tarihine kadar teslim edilmesi gerekiyor?', '18940', '8'),
    ('Araç lisans başvurusunda hangi belgelerin ve bilgilerin bulunması gerekiyor?', '20617', '16'),
    ('Emniyet yönetim sistemi ne tür bir yapıya sahip olmalıdır?', '15786', '5'),
    ('Kanunun uygulanmasına ne zaman başlar?', '4811', '21'),
    ("Danışma Kurulu'nun üyeleri kimlerdir?", '42624', '12'),
    ('Sınavlarda kopya çektirme işlemiyle ilgili ne olur?', '42587', '24'),
    ('Kapıyı kapatıp laboratuvarı geri almak için ne yaparlar?', '9650', '14'),
    ('Yatırımcılar ne zamanaşımında tazmin talebinde bulunur?', '19519', '8'),
    ('Sınav sonuçlarını itiraz etmek için ne zaman yapmam gerekiyor?', '15273', '15'),
    ('Öğrenci, özel öğrencilik hakkını nasıl kullanabilir?', '24836', '9'),
    ('Türkiye Yazma Eserler Kurumu başkanlığını kimin?', '16042', '3'),
    ('İhraç edilen arpaların muayene raporuna göre vasıflarından düşük olduğu durumlarda ne yapılır?', '212700', '23'),
    ('Atamalar sırasında neye başvurabileceğinizi anlatın?', '12445', '46'),
    ('Öğrenci, hangi tarihlerde ders kaydı yaptırmak zorundadır?', '24364', '39'),
    ('Üniversite yönetimindeki adımları hangileri?', '38344', '4'),
    ('Denetim planı hangi kişinin onayına sunulur?', '15612', '21'),
    ('Kurum hesabına kira sertifikalarını nasıl kullanırız?', '20147052', '210'),
    ('Emniyet Genel Müdürlüğü tarafından satın alınan taşıtların tasfiyesiyle ilgili ne yapacak?', '34328', '2'),
    ('Kurum, hangi yollardan piyasa faaliyetlerini denetlemek için hizmet alabilir?', '10280', '5'),
    ('Öğrenci, yaz tatiline rastlayan ayda staj yapamayacağını ne zaman öğreniyor?', '38922', '13'),
    ('Türkiye Büyük Millet Meclisi Kanunu 34/2010 maddesiyle ilgili: Basım ve yayın işlemlerini düzenleyen ne yönetmelik?', '16523', '1'),
    ('Sınıf tekrarı hakkı olan 12nci sınıf öğrencilerinden sınıf tekrarı hakkı bulunmayanların durumu nasıl değerlendirilir?', '20452', '13'),
    ('Fakülte diplomalarını veren mevzuatın hangi öğrencilere özel mi?', '42703', '10'),
    ("Türkiye'deki kalkınma merkezinin amacı nedir?", '33870', '5'),
    ('Sözleşme yapılmasında tarafların görev ve sorumluluğu hangi oranlarda belirlenir?', '34871', '24'),
    ('Banka, risk ölçüm modeliyle ilgili ne der?', '21196', '9'),
    ('Sınavlarda en az (70) puan almak için genel ortalamanın ne olması gerektiğini nezdine bakar m?', '40212', '21'),
    ('Ticari elektronik ileti onay ve ret işlemlerinde entegratörlük yetkisi ne zaman alınamaz?', '40987', 'Geçi̇ci̇ 1'),
    ('İşletmenin sahibi, ölçüm kayıtlarını en az beş yıl boyunca muhafaza eder mi?', '13184', '28'),
    ("Türkiye Yasası'nda numara taşınabilirliği uygulanmasında hangi koşulların bulunduğunu belirtir?", '13180', '5'),
    ('2547 sayılı Kanunun 13. maddesine göre, kimin önerisi üzerine Rektör tarafından personel görevlendirilir?', '36034', '16'),
    ('Türkiye gümrük bölgesine metal hurdaların girişini nasıl tespit ederler?', '42907', '7'),
    ('Uyuşmazlık yeniden başlamış mı? Eğer evi temizlemek için arabanın içini temizledim, ücret mi alacağım?', '20335', '6'),
    ('Patent başvurusu için önleme hakkı var mı?', '6769', '87'),
    ('Kültür ve turizm projelerine ne tür yardımlar sağlayacak bakanlık?', '11189', '1'),
    ('Kanunun bu maddeyi okuduktan sonra merkez ne yapmayı istemiyor?', '34777', '6'),
    ('Portföy yönetim ücreti ne tür pay grupları oluşturmakta?', '20792', '57'),
    ('Türkiye Ticaret Tebliğine göre, Brüt kg Gözetim uygulaması ne anlama geliyor?', '40052', '1'),
    ('Öngörülen bütçede ödeneklerin yetersiz olması durumunda, ek bütçe ne zaman yapılabilir?', '40734', '11'),
    ('Nasıl bir materyal ülke içinde dolaşımı için yetki belgesi düzenlenir?', '20338', '7'),
    ('Nasıl bir kılavuz kaptan alma ve bırakma yerine geçici değişiklik yapabilirsin?', '16726', '15'),
    ("Antalya'daki üniversite merkezinin görevlerini ne kapsar?", '34468', '2'),
    ('Öğrenci üniversite ile ilişkisini kesileceğini mi düşünüyor?', '22763', '30'),
    ('Memurun kadrosunun bulunduğu yerin bölge hizmetinden kaç süre sayılacak?', '18949', '11'),
    ('Denetim görüşü hangi yönlerle oluşturulur?', '15612', '13'),
    ('Öğrenci, üniversitenin belirlediği tarihlerden sonra kayıt işlemlerini tamamlamamışsa ne olur?', '42553', '12'),
    ('Gemi kontrolüne yetkili mühendis belgesi iptali durumunda hangi kurul kararlaştırır?', '14117', '9'),
    ('Ruhsat sahipleri hangi faaliyetleri içerir?', '19578', '25'),
    ('Belediye ölçüler ve ayar memurları için Bakanlık kontrol eder mi?', '3516', '20'),
    ('Eczacının ilaç kullanımına bağlı sorunlar hakkında hangi faaliyetleri yürütmesi gerekiyor?', '19569', '6'),
    ('Sınıfı geçemediğim için ikinci kez sınav hakkı verilir mi?', '33991', '39'),
    ('Öğrenci, tezli yüksek lisans programının ne süredir?', '39003', '35'),
    ('Depolama şartları uygun olmayan zeytinin lisanslı depolara nasıl alınır?', '17273', '8'),
    ('Yeni proje başvurusunda projenin toplam maliyeti ve süresi neyle ilgilidir?', '39557', '8'),
    ("Türkiye Patent ve Marka Kurumu'nda neyi Sicil olarak kaydeder?", '23927', '4'),
    ('Basılı yayınların inceleme komisyonu, eserlerinizi iade eder mi?', '33845', '8'),
    ('Nasıl zührevi hastalıklara yakalanmış kadınlar için bir yemek yapan bir ilk yardım merkezi açılır mı?', '5984', '111'),
    ('Ne zaman mecburi dava arkadaşlığına uyan durumlar olur?', '6100', '59'),
    ('Valuelerimi kiminle paylaşabilem? Yöneticileri, müşterileri, veya değerleme uzmanları?', '33762', '19'),
    ('Tahsisin sona ermesiyle, irtifak hakkı ne olur?', '10517', '29'),
    ('Kıdem, dönemi aynı olan müfettiş yardımcıları arasında nasıl belirlenir?', '34189', '50'),
    ('Hayatı sigorta edilen kişi ölmüşse sözleşme geçersiz mi?', '6102', '1487'),
    ("Üludağ Alan Yönetim Planı'nın ne içerdiğini bilmiyor musun?", '40191', '7'),
    ('Sivil savunma servislerinin görev yerlerine en kısa sürede sevk edilebilecek yer hangisidir?', '631500', '15'),
    ("İstanbul Medeniyet Üniversitesi İnsan Hakları Uygulama ve Araştırma Merkezi'nin amaçlarını ne kapsar?", '33854', '2'),
    ('Türkçe eğitim veren lisansüstü programlarında tez Türkçe yürütülür mi?', '39003', '6'),
    ('Sekretaryanın görevlerini bilmeyen bir vatandaş: "Sekretaryanın hangi görevleri var?', '15650', '14'),
    ('Müdürün görevleri ne?', '41104', '8'),
    ('Sözleşmenin feshi hangi süreçle gerçekleştirilir?', '24571', '75'),
    ('Öğrencinin davranışını değerlendiren kurulun kararı yazılmasından kimin sorumludur?', '19942', '60'),
    ("Türkiye Ticaret ve Gümrük Kanunu kapsamında, SÜGK'nın ülkeye izinsiz girişini nasıl kontrol eder?", '20827', '12'),
    ('Memelkete girmesi yasak olmıyan bitkilerin ithal edilebilmesi için hangi şartlar gereklidir?', '63346', '10'),
    ('Perakende Satıcıları için miktar sınırlaması ne?', '8712028', '93'),
    ('Bakanlık hangi kanunla uygun olarak çalışma incelemektedir?', '15233', '59'),
    ('Kişinin hangi maddeyi bilmiyor?', '34337', '34'),
    ('İşyerinde Oda-Üye ilişkilerini geliştirmek için ne kurulabilir?', '10195', '62'),
    ('Hayvan nakil araçlarının dezenfeksiyonu hangi kurum tarafından yapılır?', '15603', '29'),
    ('Ateşli silahı dikkatle muhafaza etmekten kaçınan kişi, çocukları ele geçiren nedeni belirler mi?', '6136', '13 (2)'),
    ('Eşyayı gümrük beyannamesinde nasıl ararsın?', '42521', '2'),
    ('Kabul edilebilir mi, tutukevine?', '5275', '112'),
    ('Kişinin iş bulmak konusunda hangi yerlerde memnuniyet duyması gerekiyor?', '1593', '94'),
    ('Müdür Yardımcıların görev süresi ne kadar?', '34480', '10'),
    ('Öğrenci, üniversiteden ücreti ne zaman ödemesi gerekiyor?', '40171', '9'),
    ("Türkiye Enerji Ticaret Kuralları'nda, enerji satış ihalelerinde hangi ürünler satışa sunulur?", '18946', '7'),
    ('Kanunun hangi maddesi, rektör tarafından görevlendirilecek personeli ne ile karşılaması gerekiyor?', '38251', '11'),
    ("Nafıa Vekaleti'nin hangi tesislerin harbin tesirlerinden korunmasına yardım eder?", '411635', '7'),
    ('Sınav Kurulu, başarı puanı eşit olan adamların yazılı sınav puanı yüksek olanın öncelik kazanacağına ne demek?', '34266', '14'),
    ('Öğrenci, tez önerisi savunmasında geçerli mazeret olmadan girmesini cevap verir mi?', '40302', '23'),
    ('Yetki belgesi sahipleri hangi yetkiyi vermişler?', '38528', '20'),
    ('Türkiye Ticaret Bakanlığı, Çin ithalatınıza ne karar vermiştir?', '45141', '1'),
    ('Öğrenci final sınavından en az 50 puan alamadığı için dersten başarısız sayılır mı?', '24836', '29'),
    ('Mesleğin ne olduğu?', '3568', '1'),
    ('Kadastro müdürü, listedeki davalı taşınmaz malların tespiti yapıldıktan sonra ne yapar?', '3402', '5'),
    ("Türkiye Büyük Millet Meclisi'nde ne alacak ne de borcu belirlemek için ne hesap kullanılır?", '20357', '294'),
    ('Başkanın harcama yetkilisi olduğunu nasıl bilebilir?', '45018', '17'),
    ('Öğrenci mezun olamadığını ne sebeple düşünüyor?', '24364', '17'),
    ('Ödenecek telif ve işlenme ücretleriyle ilgili maddeyi anlayan bir vatandaşın sorması: "Kapsam nedir?', '200610932', '1'),
    ('Ödediğimiz tazminat nedeniyle, ne zaman rücu edilir?', '6100', '287'),
    ('Türkiye Büyük Millet Meclisi üyeleri için hangi makam bildirimleri vermek zorundadır?', '3628', '8'),
    ('Müfettişlerin teftiş defterini hangi yetkiliye teslim ederler?', '14995', '44'),
    ('Aday memurların eğitimlerinin yapılması ve sonuçlarının bildirilmesi ne zaman ve ne şekilde yapılır?', '11105', '15'),
    ('Bakanlık, uzman ve uzman yardımcılarına araştırma yapma imkânı verir mi?', '18903', '32'),
    ('Üniversitenin ne amaçlarını belirler?', '40698', '1'),
    ('Erzurum Teknik Üniversitesi Sürekli Eğitim Uygulama ve Araştırma Merkezi hakkında ne biliyorsun?', '39002', '1'),
    ("Türkiye'deki bir akademisyen, hangi görevleriyle yükümlüdür?", '42599', '7'),
    ('Neden distile alkollü içkiler kurşun bazlı kapsülle kaplıktan satışa hazır olmaz?', '23431', '14'),
    ('Makinelerin havalandırması ne şekilde yapılmalıdır?', '13556', '53'),
    ('Daire başkanlığı seçimi ne zaman yapılır?', '6085', '14'),
    ('Bakanlık hangi laboratuvarı bir kalıntı için birden fazla veremez?', '15591', '16'),
    ('Önleme tabi ülkedeki yerleşik kapasite ve ihracat potansiyeli ne incelenmiştir?', '21546', '20'),
    ("Türkiye Büyük Millet Meclisi'nin Tebliğinin amacı nedir?", '24238', '1'),
    ('Antrepo açma ve işletme izni verilebilecek kimler?', '13472', '519'),
    ('Öngörülen amaç ve çalışma programına uygun biçimde yürütülmemiş olan projeleri durdurmak için Bakanlık ne yapar?', '19432', '27'),
    ('Öğrenci, mevzuatın ne anlama geldiğini anlayamadı: "Denetleme raporları ne zaman ve ne şekilde sunulur?', '200915134', '12'),
    ('Programların uygulama dönemi ne zaman olacak?', '15854', '55'),
    ('Öğrenci öğrenime ara verme hakkından yararlanamaz mı?', '40401', '42'),
    ('Kamu konutlarında kat mülkiyeti veya irtifak kurulması mümkün mü?', '24523', '4'),
    ('Neyle bu maddeden bahsediyorsun?', '17077', '33'),
    ('Öğrenci, hangi tarihlerde programı yenileyemem?', '39098', '6'),
    ('Geçici kabul komisyonu, işte ne tespit eder?', '12920', '7'),
    ('Yüzde ne görevleri yok, yönetim kurulu?', '42738', '11'),
    ('ÖSYM, engelli öğrencilerin sınav kılavuzuna ne tür açıklamaları hazırlamak zorunda?', '14214', '10'),
    ('Öğrenci zorunlu hazırlık sınıflarına ikinci yıl derslere katılamazsa ne olur?', '33903', '10'),
    ('Deniz sörveyi sırasında ne kontrol edilmez?', '13556', '12'),
    ('Türkiye’de yerleşik firma, kurum ve kuruluşlardan ilgili soru formuna ne yazmam gerekiyor?', '38999', '10'),
    ('Türkiye Büyük Millet Meclisi ne zaman ve neden değişiklik yapmıştır?', '11749', '2'),
    ('Fonlar hangi oranında kredi veya faizsiz finansman kullanabilir?', '19227', '23'),
    ('OSB genel idare giderleri için kredi kullanmayan durumlarda harcırah miktarı belirleyen kim?', '31245', '35'),
    ('Üniversitelerin inşaatı ve satışa giren malları hangi heyette kabul edilen yönetmeliklerle düzenlenir?', '9768', '31'),
    ('Kasa hesabında alınan çekler hesabı ne demek?', '14457', '57'),
    ('Spor dalı tescili ne tür bir işlemdir?', '42322', '47'),
    ("Gebze Teknik Üniversitesi Akıllı Tarım Uygulama ve Araştırma Merkezi'nin amaçlarını ne kapsar?", '38601', '2'),
    ("Nuh Naci Yazgan Üniversitesi'nin araştırma merkezi ne hakkında bilinmez?", '24822', '1'),
    ('Öğrenci gelirlerinden kesilen tutarın ne ile karşılaştırıldığı?', '34580', '4'),
    ('Müdür olacak kişi için hangi belgeler istenir?', '10546', '8'),
    ('Federasyon Başkanı tarafından belirlenen toplantıda hangi konular gündeme alınabilir?', '42322', '14'),
    ('Alacaklara karşı idari itiraz süresi ne zaman kesinleşmiş olur?', '20205', '3'),
    ('Kota alma ücreti belirlenmesi için hangi kurul tarafından yapılır?', '20150', '20'),
    ('Türkiye Ticaret Kanunu 30. maddede cezalandırılmamış olmak olmak üzere, Seyahat Acentası personelinin nitelikleri ne?', '11648', '34'),
    ('Kiralamalar sırasında imar tadilatı yapılmaz mı?', '14611', '5'),
    ('Nasıl Ulusal Meslek Standartları hazırlanır?', '16352', '2'),
    ('İç piyasa satış işlemlerinin ağırlıklı ortalaması esasında belirlenen normal değer hangi durumda belirlenemez?', '20142', '10'),
    ('Türkiye yerli evcil hayvan ırkı tescilinde ne tür usul ve esaslar belirlenmektedir?', '15631', '1'),
    ("Türkiye Ağırlıklı Döner Sermaye Kurumu'nda gelirlerin ve giderlerin belirlenmesinde ne olacak?", '17199', '7'),
    ('Genel müdürün teşebbüsü hakkında ne bildiğim var?', '233', '13'),
    ('Öğrenci, tez önerisiyle ilgili yazılı raporu komite üyelerine dağıtmadan önce ne yapmalıdır?', '40397', '43'),
    ('Kıyafet ikramiyesi ne kadardır?', '6320', '15'),
    ('Fonun ne için kuruldu?', '7441', '1'),
    ('Spor Federasyonu hangi tarihten itibaren yeni bir mali denetim raporu hazırlamak zorundadır?', '42466', '16'),
    ('Toplantıda gündeme alınmamış bir konu nasıl görülebilir?', '12217', '9'),
    ('Emekli bir öğretim üyesi, emekliliğe hak kazanıp emekli olan, emekli aylıklarını kesen kişinin durumu nedir?', '2547', '60'),
    ('Öğrenci ve kursiyer için ücretsiz okuma hakkı ne zaman kesilir?', '15970', '59'),
    ('Bakanlık, elektronik posta ve faks kullanamazsa, nasıl tebligat yapar?', '7140', '62'),
    ('Türk gemiadamlarının haklarını koruyan kanun ne demek?', '854', '4'),
    ('Yönetmelik ne ile ne de dayanır?', '42516', '3'),
    ('Sözleşme imzalanan hizmet alımılarında, kontrol teşkilatı üyeleri muayene ve kabul komisyonlarında görev alamaz mı?', '10453', '20'),
    ('Türkiye’deki önlemin kalkması halinde dampingli ithalatın ne olacağını düşünür misiniz?', '15857', '25'),
    ('Neden resmi sağlık kuruluşlarında yürürlükten kaldırılmıştır?', '399', '36'),
    ("Danışma Kurulu'nun görevleri nedir?", '42388', '12'),
    ("Danışma Kurulu'nun üyelerinin görev süresi kaçtır?", '31210', '9'),
    ('Öğrenci, hangi dersi almak zorundadır?', '44944', '19'),
    ('Merkezdeki sağlık hizmetlerinin kalitesinin sürekli geliştirilmesi konusunda ne yapması gerektiğini düşünüyorsun?', '40651', '9'),
    ('Öğrenci hangi dersleri tekrarlamak zorundadır?', '23341', '17'),
    ('Müfettişlik sınavından sonra altı ay içinde bir hak daha verilir, ama ne yapmaya devam ederim?', '12466', '149'),
    ("Devlet Memurları Disiplin Yönetmeliği'nde ne uygulanır?", '40026', '17'),
    ('Yeni bir lisansüstü program hangi adımları takip eder?', '38616', '7'),
    ('Devlet Memurları Kanunu ile yetiştirilmek amacına giren memurlar hakkında ne biliyorsun?', '17236', '32'),
    ('Bu maddenin cevabı olacağı bir soru: "Il müdürlüğüne damga planı ne zaman sunulmalıdır?', '18793', 'Geçi̇ci̇ 2'),
    ('Ara sınavların yazılı-sözlü veya uygulamalı olarak yapılabilir mi?', '33808', '23'),
    ('Öğrenci, paraya çevirmenin usulü ve zamanı ne olur?', '2004', '309 (7)'),
    ('Diş hekimim Odaya kaydımı sildi. Şimdi nasıl üyeliğinizi geri kazanabilirim?', '11006', '27'),
    ('Öğrenci buluşumuzda ne yapacağız?', '23927', '2'),
    ('Öğretmenlerin ve din görevlilerinin sicilleri hangi kurum tarafından tutulur?', '168', '4'),
    ("Bingöl Üniversitesi Dil Öğretimi Uygulama ve Araştırma Merkezi'nin amacı nedir?", '23115', '1'),
    ('Öğrenci, yükseköğretim kurumunun açıköğretim fakültesinden ders almayı nasıl yapabilir?', '42556', '9'),
    ("Ağrı Üniversitesi Kariyer Planlama Merkezi'nin görevleri ne?", '31329', '2'),
    ("Sınav Kurulu'nun görevi nedir?", '20873', '8'),
    ('Hangi kişilerin görevlendirilmesi ve uhdelerindeki görevleri sona ermesi gerekmektedir?', '7150', '4'),
    ('Nasıl olur kurslar 6nci maddenin ikinci fıkrasının (a) bendinde muaftır?', '23302', 'Geçi̇ci̇ 5'),
    ('İhale komisyonu üyeleri, disiplin cezası uygulanması ve tarafların zararına karşı ceza kovuşturması nedeniyle ne olur?', '14749', '70'),
    ('İzin belgesi başvurusu ne şekilde yapılır?', '42862', '5'),
    ('Tezsiz yüksek lisans programını tamamlamak için ne süreyi geçiyorum?', '45090', '15'),
    ('Ürünün ÇHC menşeli ithalatı 2013 yılında hangi seviyede gerçekleşmiştir?', '19943', '16'),
    ("Türkiye Kanunu 1234 sayılı Sürdürülebilirlik ve Arz Kurumu'nun faaliyet alanlarını ne zaman belirlendi?", '40883', '6'),
    ('Üniforma üreticisi, farklı illerde üretilen ürünlerin ihraç edileceği durumda hangi belge düzenlenir?', '15516', '8'),
    ('Üründen ne öğreniyorsun?', '39451', '4'),
    ('Kişinin hangi görevi yapmamakta endişe ediyor?', '6219', '15'),
    ('Eşyayı gümrükte muayene ederken kap numaralarını ve ayırt edici özellikleri ne şekilde sisteme kaydedilir?', '13472', '182'),
    ('Güneş enerjisine dayalı elektrik üretimini test etmek mi biliyor musun?', '15058', '1'),
    ("Türkiye Kanunu'nda, Yaşlı Bakımı Uygulama ve Araştırma Merkezi'nin görevleri hangi Yönetmelik'e bağlanır?", '42593', '2'),
    ('Türkiye’de yerleşik firma, kurum ve kuruluşlardan ilgili soru formuna ne yazmam gerekiyor?', '38727', '11'),
    ('Spor Federasyonu il temsilcisinin görev ve yetkileri hangi kurul tarafından belirlenir?', '42413', '19'),
    ('Kişinin hangi malları kiraya vermeye izin verileceğini bilmiyor?', '2886', '73'),
    ('Üyelerin oy birliğiyle karar verildiğinde, soruşturma ne zaman yürütülüyor?', '38991', '3'),
    ('Müdürün görevi sona erdiğinde, neler de sona erer?', '38437', '8'),
    ('Türkiye Kanunu 4734 sayılı, hangi alımları yapmamakta zorlanıyor?', '758', '2'),
    ('Üniversiteden istenen araştırma-geliştirme danışmanlığı ve projeleri ne tür hizmetler sunar?', '33846', '20'),
    ('Bakanlık, salgın durumlar sırasında ne yapabilir?', '39585', '19'),
    ('Köyde mera hakları kesinleşen tarihten 5 yıl sonra, itiraz edilemez mi?', '4342', '21'),
    ('Nasıl tahkikat işlemi devam ederken muafiyet kağıdı verilmez?', '21777', '28'),
    ('Başkanlıkça yıllık faaliyet raporunu yazmak için ne zaman ve ne kadar süre gerekiyor?', '34004', '75'),
    ('Yeni yıl bütçesi kesinleşmiş mi? Eğer değilse gelecek yıl bütçesi ne olur?', '5393', '66'),
    ('Öğrenci tez çalışmasında başarısız olana Enstitü ile ne ilişkisi kesilir?', '40699', '27'),
    ('Öğretim elemanı, görevlendirilmelerinde ne yapar?', '34474', '34'),
    ('Öğrenci tebligatını bildirmek için ne zaman en geç yapılmalıdır?', '40315', '11'),
    ('Üniversitede hangi fakülte ve okul yeni kurulmuştur?', '2809', 'Ek 99'),
    ('Kişinin ne yapması gerektiğini soruyor: Noterlerin ne yapmam gerektiğini?', '1512', '60'),
    ('Ön inceleme ne zaman verilmesi gerektiği?', '33753', '61'),
    ('NATO’ya bildirilmesi gereken durumlarda hangi kuruluş iletiyecektir?', '40592', '10'),
    ('Merkezin ne yaptığını biliyor musun?', '39515', '5'),
    ('Kurulun ne yapması gerektiğini biliyor musun?', '6015', '12'),
    ('Türkiye’yi dünya çapında turizm hedeflerine taşıyan Ajans, hangi yöntemle mal ve hizmet alımını yapabilir?', '40643', '5'),
    ('İstanbul ve İzmir Büyükşehir Belediyesi hangi belediyelerin hak, yetki ve görevlerini kullanır?', '3806', 'Geçici 3'),
    ('Kanun ne zaman uygulanır ve seçimler ne zaman yapılır?', '2797', 'Geçici 4'),
    ('Konsültasyonda ücretin taksimi caiz değildir mi?', '412578', '30'),
    ('İşletme sahibinin fiil ehliyeti kaybı veya ölümü, ticari temsilcilerin yetkisini neye etkiler?', '6098', '554'),
    ("Türkiye Noterler Birliği'nde çalışmak için ne zaman izin almak zorundasın?", '1512', '57'),
    ('Öğrenci yarıyıl sonu not ortalamasını hesaplamada ne yapar?', '33866', '28'),
    ('Yakıt işlerini yürütmekle yükümlü olanlar, ihmal ve kusurları neye göre cezalandırılır?', '848345', '32'),
    ('Tez izleme komitesi hangi üye tarafından atanır?', '46153', '39'),
    ('Bakanlık aile, çalışma ve sosyal hizmetler bakanlığını hangi maddede geçmektedir?', '38393', '4'),
    ('Buğday kontrol merkezlerinde ne zaman ilan edilir?', '212698', '4'),
    ('Ücret ödeme makineleriyle basılan ilan ve reklamların yapım bedeli kimin aittir?', '76156', '78'),
    ('Yeni sınav koordinatörlüğüne nasıl ödeme yapmalıyım?', '19650', '1'),
    ("Danışma Kurulu'nun üyelerinin görev süresi kaçtır?", '34919', '11'),
    ("Nasılsın? Yükseköğretim Kanunu'nun 14. maddesine dayanan yönetmelikin ne hakkında bilmiyorsun?", '38806', '3'),
    ('Subay, astsubay, uzman erbaş ve uzman jandarmalardan çalışanlara hangi tazminat ve zamların ödeneceği?', '926', 'Ek 3'),
    ('Devam etmek için orman muhafaza memurlarının atama ve yer değiştirmelerine ne anlama geliyor?', '20062', '2'),
    ('Yoldan kotlandırma ile kademelendirme işlemlerinde ada bazında değerlendirme yapılır mu?', '39703', '10'),
    ('Spor Federasyonu, hangi defterleri tutmamalıdır?', '42424', '40'),
    ('Öğretim elemanı üçüncü kademe aylığını bir yıl almamış olabilir mi?', '2914', '7'),
    ('Milli Müdafaa Vekaletinin müsaadesi olmadan, fabrika tesislerinde ne değişiklik yapılamaz?', '213992', '5'),
    ('Müdürün görevlerini nelerdir?', '34792', '10'),
    ('İhale kararının onaylanması halinde ne geçerli, ne de iptal edilirse ne?', '34894', '33'),
    ('İthalat Genel Müdürlüğü nereden bilir ki bu ithalatta haksız rekabeti araştırması tamamlandı?', '40748', '1'),
    ('Üniversite, ihale ilanını hangi yerde yayımlamak zorunlu?', '38942', '10')
]
